# Generated by Django 3.2.19 on 2023-10-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='user',
        ),
    ]
