# Generated by Django 3.2.19 on 2023-10-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageApi', '0003_auto_20231019_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='user',
        ),
    ]
