# Generated by Django 3.2.19 on 2023-10-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageApi', '0007_remove_usersubscription_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscrpitionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscrpiton_name', models.CharField(max_length=255)),
                ('subscrption_prize', models.IntegerField(null=True)),
            ],
        ),
    ]
