# Generated by Django 3.2.19 on 2023-10-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageApi', '0009_auto_20231019_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
